remote_theme: thelehhman/texture
texture:
  title: Tom치코 Milata
  tagline: Thoughts on software engineering
  social_links:
    twitter: tomas_milata
    github:  tomas-milata
    linkedIn: in/tom치코-milata-56715240/ # format: locale/username
  style: black
show_excerpts: true

